[[plugin]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_source = '''
  let g:deoplete#enable_at_startup = 1
  inoremap <expr><tab> pumvisible() ? "\<C-n>" :
        \ neosnippet#expandable_or_jumpable() ?
        \    "\<Plug>(neosnippet_expand_or_jump)" : "\<tab>"
'''
on_i = 1
depends = 'context_filetype.vim'
on_event = 'InsertEnter'

[[plugins]]
repo = 'Shougo/neosnippet'
hook_source = '''
  imap <C-o> <Plug>(neosnippet_expand_or_jump)
  smap <C-o> <Plug>(neosnippet_expand_or_jump)
  xmap <C-o> <Plug>(neosnippet_expand_target)
'''
on_i  = 1
on_ft = ['snippet']
on_event = 'InsertCharPre'
on_ft = 'snippet'
depends = ['neosnippet-snippets', 'context_filetype.vim']

